version: '3'
services:
    smart-home-ros2:
        privileged: true
        image: "unhcarl/smart_home_jackal_planner:latest"
        network_mode: host
        environment:
            - PULSE_SERVER=tcp:host.docker.internal:4713
            - TWILIO_TOKEN=$TWILIO_TOKEN
            - TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID
            - SMARTTHINGS_TOKEN=$SMARTTHINGS_TOKEN
            - TAPO_CAMERA_PASS=$TAPO_CAMERA_PASS
            - ROS_MASTER_URI=$ROS_MASTER_URI
            - ROS_IP=$ROS_IP
            - ROS_DOMAIN_ID=$ROS_DOMAIN_ID
            - APIKEY=$APIKEY
            - DISPLAY=$DISPLAY
            - FASTRTPS_DEFAULT_PROFILES_FILE=/profile/fastrtps_default_profiles.xml
        volumes:
            - /tmp/.X11-unix/:/tmp/.X11-unix/
            - ./profile:/profile
            - ./smart_home_launch.bash:/tmp/smart_home_launch.bash 
        #tty: true
        command: /tmp/smart_home_launch.bash 
        # access to 1 GPU device
   

